"""Adding model

Revision ID: 729e8095f1f5
Revises: 7a3586cd84b1
Create Date: 2024-06-12 19:27:49.149964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729e8095f1f5'
down_revision = '7a3586cd84b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('img_name', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_tasks')
    # ### end Alembic commands ###
